### PR TITLE
Change Spartacus default mirror to github.

### PR DESCRIPTION
**Pull request by th-h**
Netmirror is not very reliable currently.

Add Changelog file.

Signed-off-by: Thomas Hochstein <thh@inter.net>

### CODE REVIEW

**Comment by onli** [comment]
Necessary. Possible that we'll have to remove netmirror completely and add an upgrade-task.

**Comment by garvinhicking** [comment]
I am a bit afraid to use github by default, because I don't really fully know if what we're doing there is something they really allow us to do, so it could change any time.

netmirror is of course something that is currently not working, I tried to reach my contact there, but couldn't get a response yet.

Maybe we should default to s9y.org as our mirror...?

**Comment by th-h** [comment]
> Maybe we should default to s9y.org as our mirror...?

It was last in the list before, so I thought perhaps you wanted to save on traffic to the site. Otherwise, it would be the logical choice.

**Comment by onli** [comment]
I don't think that using github is problematic. There were articles about the performance impact of a whole programming language package manager (looked it up, it was cocoapod, see http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/). Our traffic will be minimal compared to that :)

**Comment by garvinhicking** [comment]
Yeah the thing about s9y.org always was that I had the feeling it broke more often than netmirror.... :-D

Well...we'll see I guess...

**Pull request merged**
