### PR TITLE
Unified parameter for "backend_image_add" hook

### PR DESCRIPTION
**Pull request by surrim**
* unified parameter for backend_image_add hook

### CODE REVIEW

**Comment by onli** [comment]
Hi @surrim, can you write a bit more about this change? To me it looks like a change that ought to be correct in theory but might have issues in practice, like there might be a plugin that only works with the $created_thumbnail string as the second parameter for the event hook. Does the change i nthis PR fix a bug somewhere for us?

**Comment by surrim** [comment]
I grepped all plugins for the usage of this hook. It should be safe to change the parameter value because it's not used by any plugin. If it would be used by anything, the misbehavior would be reported because it's the same hook with different parameters.

I used it for updating the file size after compressing \*.gpx files (event_static_osm). Without the media id it's hardly possible to do that.

**Comment by onli** [comment]
Grepping all plugins usually is not enough because plugins might very well not be upstreamed to us.

But this mismatch is too ugly and a possible source of bugs. Let's merge this now and keep it in mind if we get bugreports that might be caused by this.

Could you add a note to docs/NEWS describing the change?

**Comment by onli** [comment]
Thanks again @surrim, as we talked about I documented this PR this time :)

**Pull request merged**
